### ISSUE TITLE
Document the crate

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#1]
The following modules require code docs:

- [ ] src/client.rs
- [ ] src/lib.rs
- [ ] src/server.rs
- [ ] src/bytes.rs
- [ ] src/connection.rs
- [ ] src/packet/ack.rs
- [ ] src/packet/error.rs
- [ ] src/packet/opcode.rs
- [ ] src/packet/mod.rs
- [ ] src/packet/data.rs
- [ ] src/packet/mode.rs
- [ ] src/packet/rq/wrq.rs
- [ ] src/packet/rq/mod.rs
- [ ] src/packet/rq/rrq.rs
