### ISSUE TITLE
Write integration tests

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#2]
It would be beneficial to have integration tests for the following modules:

- [ ] src/client.rs
- [ ] src/server.rs
- [ ] src/connection.rs

For **src/client.rs** and **src/server.rs** I think tests for the handshake process should be sufficient (i.e, the read/write request can simply be for zero bytes)

For **src/connection.rs**, it would be nice for an integration test to fully transfer a non-zero byte amount. Ideally, coverage would include:

* connection timeouts
* a zero-byte transfer
* an n-byte transfer where n < size of a data packet
* an n-byte transfer where n spans several data packets

Note that the types in **src/connection.rs** just assume a handshake has already occurred, so the handshake doesn't have to be tested.
