### ISSUE TITLE
Add support for timeouts

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#6]
- [ ] Client should give up after not hearing from the server after a duration has elapsed
- [ ] Server should attempt to resend packets after not receiving an ack for the last one it sent after a certain time period has elapsed
- [ ] Server should give up on resending after n resent packets

You can choose the value for 'n' and/or the timeout duration.

**Comment by PurpleMyst** [comment]
Hi, I'm interested in working on this.

I was thinking that we could utilize [`UdpSocket::set_read_timeout`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.set_read_timeout) to handle the timeout, then handle the "n resent packets" case ourselves with a counter.

What do you think? If you approve, I'll get to work on this.

**Comment by connorkuehl** [comment]
That sounds like a great approach! Thank you 😀
