### ISSUE TITLE
Remove public access from packet fields and replace them with accessor methods

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#7]
The following packet modules have visible fields. The `pub` visibility qualifier should be removed and calling code should be updated to use well-crafted accessor methods.

- [ ] src/packet/ack.rs
- [ ] src/packet/error.rs
- [ ] src/packet/mod.rs
- [ ] src/packet/data.rs
- [ ] src/packet/rq/wrq.rs
- [ ] src/packet/rq/mod.rs
- [ ] src/packet/rq/rrq.rs

**Comment by itmecho** [comment]
Hi @connorkuehl, can I give this one a go as well?

**Comment by connorkuehl** [comment]
Of course, @itmecho! Thank you :smile:

**Comment by connorkuehl** [comment]
Also just as a note, this issue is labeled **meta** so feel free to open more than one PR if you'd prefer to complete this work incrementally.

**Comment by itmecho** [comment]
Great! I'm hoping to start this later in the week

**Comment by connorkuehl** [comment]
We've agreed to not add accessor methods per the conversation in #17
