### ISSUE TITLE
Actually honor mode support

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#8]
TFTP defines three modes: mail, netascii, and octet. Mail isn't used and shouldn't be implemented. We have it for completeness. However, this crate doesn't actually do anything with the mode. It simply sends and receives bytes, so I guess it just defaults to octet mode regardless of what is specified.

While I'm not sure how immediately helpful it is to distinguish between netascii and octet, but for the sake of accuracy, the mode should probably be honored.

OTOH, I think this is relevant for moving the issue forward:

- [ ] The Data packet payload will need to be ran through a filter to convert between netascii and octet
- [ ] Relevant unit tests will need to be updated
- [ ] Relevant integration tests will need to be updated

**Comment by connorkuehl** [comment]
I just re-read parts of RFC 1350. "Netascii" is 8-bit ASCII. Octet is 8-bit bytes. I don't think this issue is meaningful anymore. Or that it ever was 😅
